server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emersonhss/tcc-mba-hbcloud-configs
      discovery: 
        enabled: true
        service-id: configuration-service
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000